# Cargo configuration for the project

[build]
# Number of parallel jobs, defaults to # of CPUs
# jobs = 4

[term]
# whether cargo provides color output
color = 'auto'
# whether cargo shows progress bar
progress.when = 'auto'
progress.width = 80

[alias]
# Useful cargo aliases
check-all = "check --all-targets --all-features"
test-all = "test --all-targets --all-features"
doc-open = "doc --open --no-deps"
